local button = require "utils.button"
local monarch = require "monarch.monarch"

function init(self)
	button.acquire()
	
	button.register("btn_party", function()
		monarch.show("party")
	end)

	button.register("btn_storage", function()
		monarch.show("storage")
	end)

	button.register("btn_add", function()
		monarch.show("add")
	end)
end

function final(self)
	button.unregister()
end

function on_input(self, action_id, action)
	button.on_input(action_id, action)
end
