local monarch = require "monarch.monarch"
local url = require "utils.url"
local tracking_id = require "utils.tracking_id"

function init(self)
	msg.post(".", "acquire_input_focus")

end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.released then
		gameanalytics.addDesignEvent {
			eventId = "Navigation:Back",
			value = tracking_id[monarch.top()]
		}
		monarch.back()
	end
end