local notify = require "utils.notify"

local notify_factory

function init(self)
	notify.url = msg.url()
end


function on_message(self, message_id, message)
	if message_id == notify.MSG_NOTIFY then
		if not notify_factory then
			notify_factory = collectionfactory.create("/notification#collectionfactory")
		end
	elseif message_id == notify.MSG_DONE then
		if notify_factory then
			go.delete(notify_factory)
			notify_factory = nil
		end
	end
end