local monarch  = require "monarch.monarch"
local button = require "utils.button"
local render_order = require "utils.gui_render_order"


function init(self)
	button.acquire()
	gui.set_render_order(render_order.POPUP_ON_POPUP)
	local data = monarch.data("info")
	gui.set_text(gui.get_node("txt_info"), data.text)

	button.register("btn_close", function()
		monarch.back()
	end)
end

function on_input(self, action_id, action)
	button.on_input(action_id, action)
end
