local button = require "utils.button"
local monarch = require "monarch.monarch"

function init(self)
	gui.set_render_order(5)
	button.acquire()
	local data = monarch.data("info")
	gui.set_text(gui.get_node("description"), data.txt)
	button.register("background", function()
		monarch.back()
	end)
end

function final(self)
	button.unregister()
end

function on_input(self, action_id, action)
	button.on_input(action_id, action)
end
