local M = {}


M.RANDOM_POKEMON        = hash("random_pokemon")
M.PARTY                 = hash("party")
M.GENERATE_POKEMON      = hash("generate_pokemon")
M.SPLASH                = hash("splash")
M.STORAGE               = hash("storage")
M.PICK_NAME             = hash("pick_name")
M.VERSION               = hash("version")
M.MOVES_SCROLLIST       = hash("moves_scrollist")
M.ARE_YOU_SURE          = hash("are_you_sure")
M.SCROLLIST             = hash("scrollist")
M.INFO                  = hash("info")
M.IMPORT                = hash("import")
M.ADD                   = hash("add")
M.PROFILES              = hash("profiles")
M.POKEDEX               = hash("pokedex")
M.SETTINGS              = hash("settings")
M.TRAINER               = hash("trainer")
M.DEBUG                 = hash("debug")
M.INPUT                 = hash("input")
M.MOVE_INFO             = hash("move_info")
M.STATUS_EFFECTS        = hash("status_effects")
M.EDIT                  = hash("edit")
M.POKEDEX_POKEMON       = hash("pokedex_pokemon")
M.IMPORT_POKEMON        = hash("import_pokemon")
M.FAKEMON               = hash("fakemon")
M.TRANSFER_POKEMON      = hash("transfer_pokemon")
M.SORTING               = hash("sorting")
M.SPLASH                = hash("splash")
M.NATURES_SCROLLIST     = hash("natures_scrollist")
M.MOVES_SCROLLIST       = hash("moves_scrollist")
M.ABOUT                 = hash("about")
M.MOVES_CONFIRM         = hash("moves_confirm")
M.RECEIVE               = hash("receive")
M.NETWORK_CONNECT       = hash("network_connect")
M.NETWORK_CHOOSE_MEMBER = hash("network_choose_member")
M.NETWORK_START_HOSTING = hash("network_start_hosting")
M.NETWORK_JOIN_HOST     = hash("network_join_host")


return M