local M = {}


M.RANDOM_POKEMON        = "random_pokemon"
M.PARTY                 = "party"
M.GENERATE_POKEMON      = "generate_pokemon"
M.SPLASH                = "splash"
M.STORAGE               = "storage"
M.PICK_NAME             = "pick_name"
M.VERSION               = "version"
M.MOVES_SCROLLIST       = "moves_scrollist"
M.ARE_YOU_SURE          = "are_you_sure"
M.SCROLLIST             = "scrollist"
M.INFO                  = "info"
M.IMPORT                = "import"
M.ADD                   = "add"
M.PROFILES              = "profiles"
M.POKEDEX               = "pokedex"
M.SETTINGS              = "settings"
M.TRAINER               = "trainer"
M.DEBUG                 = "debug"
M.INPUT                 = "input"
M.MOVE_INFO             = "move_info"
M.STATUS_EFFECTS        = "status_effects"
M.EDIT                  = "edit"
M.POKEDEX_POKEMON       = "pokedex_pokemon"
M.IMPORT_POKEMON        = "import_pokemon"
M.FAKEMON               = "fakemon"
M.TRANSFER_POKEMON      = "transfer_pokemon"
M.SORTING               = "sorting"
M.SPLASH                = "splash"
M.NATURES_SCROLLIST     = "natures_scrollist"
M.MOVES_SCROLLIST       = "moves_scrollist"
M.ABOUT                 = "about"


return M